spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.118/US_db?characterEncoding=utf-8&useSSL=false
  redis:
      host: 192.168.1.118
      port: 6379

#server:
#  context-path: /US
